In [1]:
# IEX API Call test

In [2]:
# Import libraries and dependencies
import os
import requests
import pandas as pd
import json

from dotenv import load_dotenv
load_dotenv()

%matplotlib inline

In [3]:
iex_api_key = os.getenv("IEX_API_KEY")
iex_test_api_key = os.getenv("IEX_TEST_API_KEY")

In [17]:
base_url = 'https://cloud.iexapis.com/v1/'
sandbox_url = 'https://sandbox.iexapis.com/stable/'


token = os.environ.get('IEX_API_KEY')
test_token = os.environ.get('IEX_TEST_API_KEY')
params = {'token': token}
test_params = {'token': test_token}

"""
https://sandbox.iexapis.com/stable/stock/IBM/quote?token=YOUR_TEST_TOKEN_HERE
"""

'\nhttps://sandbox.iexapis.com/stable/stock/IBM/quote?token=YOUR_TEST_TOKEN_HERE\n'

In [5]:
resp = requests.get(base_url + 'status')
resp

In [6]:
resp.json()

{'status': 'up',
 'version': '1.32',
 'time': 1632355004433,
 'currentMonthAPICalls': 22405873819}

In [7]:
resp = requests.get(sandbox_url+'stock/AAPL/chart', params=test_params)
resp

In [8]:
data = resp.json()

In [9]:
data = json.dumps(data, indent=4)
df = pd.DataFrame(resp.json())
df.head()

,close,high,low,open,symbol,volume,id,key,subkey,date,...,uLow,uVolume,fOpen,fClose,fHigh,fLow,fVolume,label,change,changePercent
0,149.75,157.27,148.45,148.45,AAPL,60874478,RRTSIOC_HIICLAEPS,LPAA,,2021-08-23,...,149.56,60389983,155.62,156.72,150.67,153.74,61795784,"Aug 23, 21",0.000000,0.0000
1,153.16,155.26,150.56,150.56,AAPL,50661401,CHRRT_IIAOLSIPCSE,LAPA,,2021-08-24,...,149.75,50398807,156.27,154.63,155.40,149.52,50255332,"Aug 24, 21",-0.094188,-0.0006
2,152.88,154.94,149.00,150.16,AAPL,59485408,SORTHEPIICSC_RAIL,APLA,,2021-08-25,...,151.60,59197850,151.13,149.50,150.44,152.50,59597922,"Aug 25, 21",-1.298639,-0.0085
3,153.25,153.25,147.98,150.75,AAPL,48851489,TIIIAOLRE_PCSCSHR,AALP,,2021-08-26,...,148.35,50941424,150.55,150.83,151.04,151.05,48923501,"Aug 26, 21",-0.825005,-0.0057
4,152.20,152.89,150.56,152.89,AAPL,56285918,_IICERSRCHOTAPLSI,PLAA,,2021-08-27,...,153.09,56988200,148.36,152.50,154.47,151.87,55856628,"Aug 27, 21",1.085951,0.0073

In [18]:
def call_test_api(stock_ticker):
    
    resp = requests.get(sandbox_url+'stock/'+stock_ticker+'/chart',params=test_params)
    return resp

def call_api(stock_ticker):
    
    resp = requests.get(base_url+'stock/'+stock_ticker+'/chart', params=params)
    return resp

In [19]:
tsla_resp = call_test_api("TSLA")
tsla_resp

In [16]:
tsla_df = pd.DataFrame(tsla_resp.json())
tsla_df.head()

,close,high,low,open,symbol,volume,id,key,subkey,date,...,uLow,uVolume,fOpen,fClose,fHigh,fLow,fVolume,label,change,changePercent
0,706.30,712.1299,680.7505,685.442,TSLA,20264859,HISTORICAL_PRICES,TSLA,,2021-08-23,...,680.7505,20264859,685.442,706.30,712.1299,680.7505,20264859,"Aug 23, 21",0.00,0.0000
1,708.49,715.2200,702.6400,710.680,TSLA,13083071,HISTORICAL_PRICES,TSLA,,2021-08-24,...,702.6400,13083071,710.680,708.49,715.2200,702.6400,13083071,"Aug 24, 21",2.19,0.0031
2,711.20,716.9700,704.0000,707.030,TSLA,12645562,HISTORICAL_PRICES,TSLA,,2021-08-25,...,704.0000,12645562,707.030,711.20,716.9700,704.0000,12645562,"Aug 25, 21",2.71,0.0038
3,701.16,715.4000,697.6201,708.310,TSLA,13214292,HISTORICAL_PRICES,TSLA,,2021-08-26,...,697.6201,13214292,708.310,701.16,715.4000,697.6201,13214292,"Aug 26, 21",-10.04,-0.0141
4,711.92,715.0000,702.1001,705.000,TSLA,13833763,HISTORICAL_PRICES,TSLA,,2021-08-27,...,702.1001,13833763,705.000,711.92,715.0000,702.1001,13833763,"Aug 27, 21",10.76,0.0153

In [13]:
tsla_resp = call_api("TSLA")
tsla_resp

In [15]:
tsla_df = pd.DataFrame(tsla_resp.json())
tsla_df.set_index('date')
tsla_df.head()

,close,high,low,open,symbol,volume,id,key,subkey,date,...,uLow,uVolume,fOpen,fClose,fHigh,fLow,fVolume,label,change,changePercent
0,706.30,712.1299,680.7505,685.442,TSLA,20264859,HISTORICAL_PRICES,TSLA,,2021-08-23,...,680.7505,20264859,685.442,706.30,712.1299,680.7505,20264859,"Aug 23, 21",0.00,0.0000
1,708.49,715.2200,702.6400,710.680,TSLA,13083071,HISTORICAL_PRICES,TSLA,,2021-08-24,...,702.6400,13083071,710.680,708.49,715.2200,702.6400,13083071,"Aug 24, 21",2.19,0.0031
2,711.20,716.9700,704.0000,707.030,TSLA,12645562,HISTORICAL_PRICES,TSLA,,2021-08-25,...,704.0000,12645562,707.030,711.20,716.9700,704.0000,12645562,"Aug 25, 21",2.71,0.0038
3,701.16,715.4000,697.6201,708.310,TSLA,13214292,HISTORICAL_PRICES,TSLA,,2021-08-26,...,697.6201,13214292,708.310,701.16,715.4000,697.6201,13214292,"Aug 26, 21",-10.04,-0.0141
4,711.92,715.0000,702.1001,705.000,TSLA,13833763,HISTORICAL_PRICES,TSLA,,2021-08-27,...,702.1001,13833763,705.000,711.92,715.0000,702.1001,13833763,"Aug 27, 21",10.76,0.0153

In [ ]:
## tsla_annual         &period={} 
stock_ticker = "TSLA"
tsla_annl_resp = requests.get(base_url+'stock/'+stock_ticker+'/chart/', params=params)


https://cloud.iexapis.com/stable/stock/IBM/financials?token=YOUR_TOKEN_HERE&period=annual